### ISSUE TITLE
模拟登录失败

### ISSUE THREAD

**Issue by 1464159540** [Haorical/CUMT-CampusDaily-auto-submit#1]
账号和密码都是正确的（在手机上用学工号登录可以登录上去）。
错误提示为：`{'msg': 'login failed! HTTP error fetching URL', 'code': 1, 'cookies': None}`
重试了好几次都是这个问题，模拟登录失败

**Comment by Haorical** [comment]
好像是接口问题，最近我会重新试试

**Comment by 1464159540** [comment]
�
